
chain_name: map_reduce
map_template: 'Ты - эксперт в области обработки текста. Твоя задача – создать краткое
  содержание для предоставленного фрагмента транскрипта встречи (буллет-поинты). Сфокусируйся
  на ключевых решениях, договоренностях и итогах, избегая лишней информации.
  Инструкции:
  1. Прочитай предоставленный фрагмент транскрипта.
  2. Выдели и перечисли ключевые моменты, включая итоги, договоренности и решения.
  3. Группируй информацию по темам, если возможно.
  Структура ответа:
  "
  <Тема 1>:
  - <Пункт 1>
  - <Пункт 2>
  ...
  - <Пункт N>
  <Тема 2>:
  - <Пункт 1>
  - <Пункт 2>
  ...
  "
  Примеры ответа:
  "
  Обновление продукта:
  - новая страница подписки
  - улучшено саммари в отчете
  - повышена производительность продукта
  Конференции и встречи:
  - в среду встреча с Х в 20:00
  - с конференции Y пришло 2 новых клиента
  Статусы задач:
  - задача по редизайну страницы завершена
  - анализ рынка выполнен на 80%
  - отчет будет готов к пятнице
  Итоги встречи:
  - согласованы сроки выполнения задач
  - уточнены ответственные за каждую задачу
  - все участники согласились с предложенным планом
  - следующая встреча назначена на 15 июня
  "
  Фрагмент транскрипта:
  "
  {docs}
  "
  Краткое содержание (без кавычек):'
reduce_template: 'Ты - эксперт в области обработки текста. Твоя задача – создать краткое
  содержание для предоставленного фрагмента транскрипта встречи (буллет-поинты). Сфокусируйся
  на ключевых решениях, договоренностях и итогах, избегая лишней информации.
  Инструкции:
  1. Прочитай предоставленный фрагмент транскрипта.
  2. Выдели и перечисли ключевые моменты, включая итоги, договоренности и решения.
  3. Группируй информацию по темам, если возможно.
  Структура ответа:
  "
  <Тема 1>:
  - <Пункт 1>
  - <Пункт 2>
  ...
  - <Пункт N>
  <Тема 2>:
  - <Пункт 1>
  - <Пункт 2>
  ...
  "
  Примеры ответа:
  "
  Обновление продукта:
  - новая страница подписки
  - улучшено саммари в отчете
  - повышена производительность продукта
  Конференции и встречи:
  - в среду встреча с Х в 20:00
  - с конференции Y пришло 2 новых клиента
  Статусы задач:
  - задача по редизайну страницы завершена
  - анализ рынка выполнен на 80%
  - отчет будет готов к пятнице
  Итоги встречи:
  - согласованы сроки выполнения задач
  - уточнены ответственные за каждую задачу
  - все участники согласились с предложенным планом
  - следующая встреча назначена на 15 июня
  "
  Фрагмент транскрипта:
  "
  {docs}
  "
  Краткое содержание (без кавычек):'
question_template: ""
refine_template: ""
